### ISSUE TITLE
Transformation fails for artifact 'com.google.javascript:closure-compiler:v20211201'

### ISSUE THREAD

**Issue by michael-spahn** [jjohannes/extra-java-module-info#23]
`Failed to transform closure-compiler-v20211201.jar (com.google.javascript:closure-compiler:v20211201) to match attributes {artifactType=jar, javaModule=true, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
Execution failed for ExtraModuleInfoTransform: [...]/closure-compiler-v20211201.jar.
java.util.zip.ZipException: duplicate entry: META-INF/MANIFEST.MF
duplicate entry: META-INF/MANIFEST.MF`

I assume the published jar file is corrupt, but it's still working otherwise. So it would be nice if this plugin could be a bit more lenient with such issues.

**Comment by jjohannes** [comment]
Thanks for reporting. 

The Jar is corrupt, because the MANIFEST is not in the right place. As far as I know, it needs to be the first entry in the archive.

Because of that, the Manifest is not found and the plugin will create a new one. I pushed this fix to remove the "broken" Manifest completely from the transformed Jar:
https://github.com/jjohannes/extra-java-module-info/commit/ed393c4e3ce8683cb1516610368a2f3d787ac9a1#diff-876d21a05386747b140e7fe2fe699385add20f6ac3589e3f281a436c1f53d25d

Instead, the transformed Jar will contain a new Manifest in the correct position with the _automatic module name_ entry.

Is that what you would had in mind?

**Comment by jjohannes** [comment]
Fix is published in version `0.10`

**Comment by michael-spahn** [comment]
@jjohannes Perfect, thanks!
